### PR TITLE
Bug vision doesnt detect agents

### PR DESCRIPTION
**Pull request by Jolijn2020**

### CODE REVIEW

**Comment by trav-d13** [comment]
closes #333

**Comment by MatthewFoster02** [comment]
Weird

The rays seem to be weird here. Also they can see the target flag through walls and even other agents through walls (not shown here). If an agent or the target flag is behind an agent, their rays get reversed for the small section that can see the agent behind.

**Comment by Jolijn2020** [comment]
> Weird
> 
> The rays seem to be weird here. Also they can see the target flag through walls and even other agents through walls (not shown here). If an agent or the target flag is behind an agent, their rays get reversed for the small section that can see the agent behind.

I think I know why that is, I'll try to fix it in a bit. If it is what I think it is, it shouldn't take too long to fix, but gotta finish something else first.

Will get back to you in at most 2 hours.

**Review by trav-d13 — APPROVED** [review]
Everything works my side

**Review by trav-d13 — APPROVED** [review]

**Review by MatthewFoster02 — APPROVED** [review]
Runs on my side. Wouldn't merge until other people who didn't help with the final changes have reviewed.

**Comment by Jolijn2020** [comment]
everyone has reviewed now, right?

**Pull request merged**
