### PR TITLE
Agent capture imp

### PR DESCRIPTION
**Pull request by mahshidghaffari**
@reviewer 
this PR is a initial implementation of capturing agent, 
and almost each function has comment

### CODE REVIEW

**Comment by S010MON** [comment]
Mahshid told me this was still a draft ... is that right?

**Comment by MatthewFoster02** [comment]
I know that it is just the basics but once this is merged I think @mahshidghaffari and I can create a new branch to work in for the other features. My fault that I did not communicate to Mahshid about me un-drafting this.

**Review by trav-d13 — APPROVED** [review]
Looks good! 
Let me know when and how I can help integrate the capture implementation with the Aco agent so they work together.

**Comment by MatthewFoster02** [comment]
This PR is ready to be reviewed!

I apologise for this being such a huge merge, will definitely create more frequent PR's in future to keep merging incremental changes.

As always let me know additions, changes and improvements as you find them and they shall be considered and implemented ASAP.

To see capturing occur;
1. Enable capturing in GameEngine.
2. Disable human in Map.
3. Create the initial position for the intruder before creating each type of agent.
4. When creating the guard agents, create a capture agent and give it the initial position of the intruder.
5. When creating the intruder agents, pass the initial position created earlier as its starting position.
6. Right now, in order for the capture agent to see the intruder, the radius should be set at 50. This is a known bug and has a draft PR already @Jolijn2020.
7. Run the TestCapture map.

**Review by GwenTinho — APPROVED** [review]

**Pull request merged**
