### PR TITLE
324 Encode Sate Changes

### LINKED ISSUE #324: Encode-State-Changes

### PR DESCRIPTION
**Pull request by S010MON**
closes #324 encodes main state changes for Guards (ACO) and Intruders (WF) within the `AgentImp` class, returning state changes (from `EvasionAgent`, `TargetAgent`, and `CaptureAgent`) are encoded specifically for each class.  They are currently hard coded to return to the default Guard/Intruder states as outlined above.

Known issues:

1. **Capture Agent**.  Caused when an guard sees an intruder through glass but is unable to move through the glass.  Stack trace below
```Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "app.controller.linAlg.Vector.sub(app.controller.linAlg.Vector)" because "wantedMove" is null
	at app@1.0/app.model.agents.Capture.CaptureAgent.shortTermMemory(CaptureAgent.java:113)
	at app@1.0/app.model.agents.Capture.CaptureAgent.move(CaptureAgent.java:67)
	at app@1.0/app.controller.GameEngine.tick(GameEngine.java:62)
	at app@1.0/app.controller.GameEngine.lambda$new$0(GameEngine.java:37)
	at javafx.graphics/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at javafx.graphics/com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.graphics/javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.graphics/javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at javafx.graphics/com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:104)
	at javafx.graphics/javafx.animation.Animation.doTimePulse(Animation.java:1189)
	at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:207)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/javafx.animation.Animation$1.timePulse(Animation.java:206)
	at javafx.graphics/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at javafx.graphics/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:571)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

2. **CaptureAgent ->  ACO**. Currently state change not working, being investigated.

### CODE REVIEW

**Comment by trav-d13** [comment]
Build is succesful my side. 
I then ran the simulation, it showed a successful transition to Capture. 
However a bug was then produced.
error
I'm unsure if this is related to the state change or something in WF

**Comment by MatthewFoster02** [comment]
Update on the bugs, the capture agent bug was fixed by @Jolijn2020 so no more null pointer exceptions, although the agent can still be refactored to better deal with glass.

The bug Travis and I found only occurs in the WF agent that is coming from the capture agent. Transition between target agent and WF agents are seamless.

**Comment by Jolijn2020** [comment]
> Update on the bugs, the capture agent bug was fixed by @Jolijn2020 so no more null pointer exceptions, although the agent can still be refactored to better deal with glass.


The dealing with glass will be smoother once we can see glass (possible with big vision change that we'll do when phase 2 finishes

**Comment by Jolijn2020** [comment]
transition from CaptureAgent to ACO-agent works now.
When I did the correct world transition in WF-agent, I also did it in ACO-agent.
I get no errors for either anymore

**Review by Jolijn2020 — APPROVED** [review]

**Pull request merged**
